export type AITool = { name: string; slug: string; description: string; category: string; bestFor: string; tags: string[]; url: string; affiliate?: boolean };

export const AI_TOOL_CATEGORIES = ['AI Assistants','Coding & Development','App Builders','Image Generation','Video','Audio & Voice','Writing & Content','Research','Productivity','Automation','Design'] as const;

export const AI_TOOLS: AITool[] = [
  { name:'ChatGPT', slug:'chatgpt', category:'AI Assistants', bestFor:'General-purpose AI assistance', description:'A general-purpose AI assistant for writing, analysis, coding, research, and everyday tasks.', tags:['assistant','writing','coding','research'], url:'https://chatgpt.com' },
  { name:'Claude', slug:'claude', category:'AI Assistants', bestFor:'Long-form thinking and writing', description:'An AI assistant for writing, analysis, reasoning, coding, and large-context work.', tags:['assistant','writing','reasoning','coding'], url:'https://claude.ai' },
  { name:'Grok', slug:'grok', category:'AI Assistants', bestFor:'Conversational AI and current information', description:'An AI assistant from xAI for conversation, reasoning, research, and creative tasks.', tags:['assistant','research','reasoning'], url:'https://grok.com' },
  { name:'Gemini', slug:'gemini', category:'AI Assistants', bestFor:'Google-connected AI assistance', description:'Google’s AI assistant for conversation, writing, analysis, research, and multimodal work.', tags:['assistant','google','research','multimodal'], url:'https://gemini.google.com' },
  { name:'Perplexity', slug:'perplexity', category:'Research', bestFor:'AI-powered web research', description:'An AI search and research platform designed to answer questions using web sources.', tags:['search','research','citations'], url:'https://www.perplexity.ai' },
  { name:'NotebookLM', slug:'notebooklm', category:'Research', bestFor:'Researching your own sources', description:'A research assistant that works from documents and other sources you provide.', tags:['research','documents','notes'], url:'https://notebooklm.google.com' },
  { name:'Replit', slug:'replit', category:'App Builders', bestFor:'Building and publishing apps with AI', description:'An AI-powered development environment for creating, editing, and deploying applications.', tags:['coding','app-builder','deployment','ai'], url:'https://replit.com/refer/johnp628?trackingContext=referral-banner', affiliate:true },
  { name:'Polsia', slug:'polsia', category:'App Builders', bestFor:'Building AI-powered businesses and apps', description:'An AI-native platform for building and operating software products and businesses.', tags:['app-builder','business','ai-agent'], url:'https://polsia.com/?ref=A4GME9RG', affiliate:true },
  { name:'Cursor', slug:'cursor', category:'Coding & Development', bestFor:'AI-assisted software development', description:'An AI-first code editor designed to help developers understand, write, and modify code.', tags:['coding','developer','editor'], url:'https://www.cursor.com' },
  { name:'Lovable', slug:'lovable', category:'App Builders', bestFor:'Rapid web app prototyping', description:'An AI-powered app builder for turning natural-language ideas into working web applications.', tags:['app-builder','web-app','prototype'], url:'https://lovable.dev' },
  { name:'Bolt', slug:'bolt', category:'App Builders', bestFor:'Prompt-to-app development', description:'An AI development environment for generating and running web applications from natural language.', tags:['app-builder','coding','web-app'], url:'https://bolt.new' },
  { name:'v0', slug:'v0', category:'App Builders', bestFor:'Generating modern web interfaces', description:'An AI interface and application generator focused on modern web development.', tags:['ui','coding','web-app'], url:'https://v0.dev' },
  { name:'Midjourney', slug:'midjourney', category:'Image Generation', bestFor:'AI-generated visual concepts', description:'A generative AI platform focused on creating images and visual concepts from prompts.', tags:['images','art','creative'], url:'https://www.midjourney.com' },
  { name:'Adobe Firefly', slug:'adobe-firefly', category:'Image Generation', bestFor:'Generative creative work', description:'Adobe’s generative AI tools for creating and editing images and creative assets.', tags:['images','design','adobe'], url:'https://firefly.adobe.com' },
  { name:'Canva', slug:'canva', category:'Design', bestFor:'Fast visual content creation', description:'A visual design platform with AI features for presentations, graphics, social content, and more.', tags:['design','social','presentations'], url:'https://www.canva.com' },
  { name:'Recraft', slug:'recraft', category:'Image Generation', bestFor:'Design-focused image generation', description:'An AI design platform for generating and editing images, graphics, and visual assets.', tags:['images','design','graphics'], url:'https://www.recraft.ai' },
  { name:'Runway', slug:'runway', category:'Video', bestFor:'Generative video creation', description:'A generative AI creative platform for producing and editing video and other visual media.', tags:['video','generation','creative'], url:'https://runwayml.com' },
  { name:'HeyGen', slug:'heygen', category:'Video', bestFor:'AI avatar and presenter videos', description:'A video platform for creating AI avatar, presenter, translation, and marketing videos.', tags:['video','avatars','marketing'], url:'https://www.heygen.com' },
  { name:'ElevenLabs', slug:'elevenlabs', category:'Audio & Voice', bestFor:'AI voice and speech', description:'A generative audio platform focused on realistic speech, voice tools, and audio creation.', tags:['voice','audio','tts'], url:'https://elevenlabs.io' },
  { name:'Suno', slug:'suno', category:'Audio & Voice', bestFor:'AI music creation', description:'A generative music platform for creating songs and musical ideas with AI.', tags:['music','audio','creative'], url:'https://suno.com' },
  { name:'Descript', slug:'descript', category:'Audio & Voice', bestFor:'Editing audio and video like text', description:'A media editor combining transcription, text-based editing, recording, and AI features.', tags:['video','audio','transcription'], url:'https://www.descript.com' },
  { name:'Gamma', slug:'gamma', category:'Productivity', bestFor:'AI-generated presentations and documents', description:'An AI workspace for creating presentations, documents, and visual content quickly.', tags:['presentations','documents','productivity'], url:'https://gamma.app' },
  { name:'Zapier', slug:'zapier', category:'Automation', bestFor:'Connecting apps and automating workflows', description:'An automation platform that connects apps and services to automate repetitive work.', tags:['automation','integrations','workflow'], url:'https://zapier.com' },
  { name:'Make', slug:'make', category:'Automation', bestFor:'Visual workflow automation', description:'A visual automation platform for connecting services and building multi-step workflows.', tags:['automation','workflow','integrations'], url:'https://www.make.com' },
  { name:'n8n', slug:'n8n', category:'Automation', bestFor:'Flexible AI and workflow automation', description:'A workflow automation platform suited to programmable automations and AI workflows.', tags:['automation','workflow','ai','developer'], url:'https://n8n.io' },
  { name:'Poe', slug:'poe', category:'AI Assistants', bestFor:'Accessing multiple AI models in one place', description:'A platform for chatting with and exploring a range of AI models and bots.', tags:['assistant','models','chat'], url:'https://poe.com' },
];
